import uuid

_H1 = "https://images.pexels.com/photos/9154411/pexels-photo-9154411.jpeg"
_H2 = "https://images.unsplash.com/photo-1520170350707-b2da59970118"
_H3 = "https://images.unsplash.com/photo-1546435770-a3e426bf472b"
_H4 = "https://images.unsplash.com/photo-1583394838336-acd977736f90"
_S1 = "https://images.unsplash.com/photo-1507878566509-a0dbe19677a5"
_S2 = "https://images.unsplash.com/photo-1589003077984-894e133dabab"
_S3 = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1"
_E1 = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df"
_E2 = "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46"
_W1 = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a"
_W2 = "https://images.unsplash.com/photo-1523275335684-37898b6baf30"
_A1 = "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9"
_A2 = "https://images.unsplash.com/photo-1591290619762-c588f8f4dd6b"


def _p(**kw):
    d = {
        "id": str(uuid.uuid4()),
        "currency": "EUR",
        "gallery": [],
        "specs": {},
        "colors": [],
        "stock": 42,
        "rating": 4.8,
        "reviews": 0,
        "featured": False,
        "badge": None,
        "old_price": None,
    }
    d.update(kw)
    if not d.get("gallery"):
        d["gallery"] = [d["image"]]
    return d


SEED_PRODUCTS = [
    _p(
        slug="volt-aura-max",
        name="AURA MAX",
        brand="VOLT",
        category="Casti",
        price=449.0,
        old_price=529.0,
        tagline="Anularea zgomotului redefinita",
        description="Casti over-ear flagship cu anulare activa a zgomotului de generatia a treia, drivere planar-magnetice de 40mm si pana la 40 de ore de autonomie. Confort premium pentru sesiuni infinite de ascultare.",
        image=_H1,
        gallery=[_H1, _H2],
        specs={"Drivere": "40mm planar", "Autonomie": "40h", "ANC": "Adaptiv Gen 3", "Conectivitate": "Bluetooth 5.4", "Greutate": "285g"},
        colors=["#0A0A0A", "#8A8A8F", "#E63946"],
        rating=4.9,
        reviews=1284,
        featured=True,
        badge="Best Seller",
    ),
    _p(
        slug="volt-aura-studio",
        name="AURA STUDIO",
        brand="VOLT",
        category="Casti",
        price=329.0,
        tagline="Sunet de referinta pentru creatori",
        description="Casti de studio cu raspuns in frecventa neutru, ideale pentru mixaj si mastering. Constructie robusta din aluminiu si perne cu memory foam.",
        image=_H2,
        gallery=[_H2, _H1],
        specs={"Drivere": "45mm dinamic", "Autonomie": "35h", "Impedanta": "32 Ohm", "Conectivitate": "USB-C + Jack 3.5mm", "Greutate": "310g"},
        colors=["#0A0A0A", "#1E1E22"],
        rating=4.7,
        reviews=642,
        featured=True,
    ),
    _p(
        slug="volt-nova-anc",
        name="NOVA ANC",
        brand="VOLT",
        category="Casti",
        price=219.0,
        tagline="Libertate wireless, zi de zi",
        description="Casti wireless lejere cu ANC hibrid si incarcare rapida. 15 minute pentru 5 ore de redare.",
        image=_H3,
        gallery=[_H3],
        specs={"Drivere": "40mm", "Autonomie": "30h", "ANC": "Hibrid", "Incarcare rapida": "15min = 5h", "Greutate": "250g"},
        colors=["#F3F4F6", "#0A0A0A"],
        rating=4.6,
        reviews=921,
        badge="Nou",
    ),
    _p(
        slug="volt-eclipse-pro",
        name="ECLIPSE PRO",
        brand="VOLT",
        category="Casti",
        price=549.0,
        tagline="Editia limitata audiofil",
        description="Casti open-back de top pentru audiofili, cu scena sonora vasta si detaliu extraordinar. Cablu detasabil placat cu argint.",
        image=_H4,
        gallery=[_H4],
        specs={"Tip": "Open-back", "Drivere": "50mm", "Impedanta": "300 Ohm", "Frecventa": "5Hz - 51kHz", "Greutate": "340g"},
        colors=["#1E1E22", "#8A8A8F"],
        rating=5.0,
        reviews=203,
        featured=True,
        badge="Editie limitata",
    ),
    _p(
        slug="volt-pulse-360",
        name="PULSE 360",
        brand="VOLT",
        category="Boxe",
        price=299.0,
        old_price=349.0,
        tagline="Sunet imersiv 360 de grade",
        description="Boxa portabila premium cu sunet omnidirectional, bass profund si rezistenta la apa IP67. Autonomie de 24 de ore.",
        image=_S1,
        gallery=[_S1, _S2],
        specs={"Putere": "60W RMS", "Autonomie": "24h", "Rezistenta": "IP67", "Conectivitate": "Bluetooth 5.3", "Greutate": "1.1kg"},
        colors=["#0A0A0A", "#E63946", "#8A8A8F"],
        rating=4.8,
        reviews=756,
        featured=True,
        badge="Best Seller",
    ),
    _p(
        slug="volt-monolith",
        name="MONOLITH",
        brand="VOLT",
        category="Boxe",
        price=899.0,
        tagline="Statie de sunet pentru living",
        description="Boxa de podea cu amplificare hi-fi, control multi-room si asistent vocal integrat. Piesa centrala pentru orice sistem audio.",
        image=_S2,
        gallery=[_S2],
        specs={"Putere": "150W RMS", "Difuzoare": "3 cai", "Multi-room": "Da", "Conectivitate": "WiFi + Bluetooth + AirPlay 2", "Inaltime": "78cm"},
        colors=["#0A0A0A", "#F3F4F6"],
        rating=4.9,
        reviews=118,
    ),
    _p(
        slug="volt-cube-mini",
        name="CUBE MINI",
        brand="VOLT",
        category="Boxe",
        price=129.0,
        tagline="Sunet mare, format mic",
        description="Boxa compacta de birou cu un punch surprinzator. Perfecta pentru orice spatiu.",
        image=_S3,
        gallery=[_S3],
        specs={"Putere": "20W RMS", "Autonomie": "12h", "Rezistenta": "IP54", "Conectivitate": "Bluetooth 5.2", "Greutate": "480g"},
        colors=["#E63946", "#0A0A0A", "#F3F4F6"],
        rating=4.5,
        reviews=1042,
        badge="Nou",
    ),
    _p(
        slug="volt-drift-buds",
        name="DRIFT BUDS",
        brand="VOLT",
        category="Casti In-Ear",
        price=179.0,
        tagline="Casti true-wireless cu ANC",
        description="Casti in-ear compacte cu anulare activa a zgomotului, sunet adaptiv si pana la 30 de ore cu carcasa de incarcare.",
        image=_E1,
        gallery=[_E1],
        specs={"Drivere": "11mm", "Autonomie": "8h + 22h", "ANC": "Adaptiv", "Rezistenta": "IPX4", "Incarcare": "USB-C + Wireless"},
        colors=["#0A0A0A", "#F3F4F6", "#E63946"],
        rating=4.7,
        reviews=2140,
        featured=True,
        badge="Best Seller",
    ),
    _p(
        slug="volt-drift-sport",
        name="DRIFT SPORT",
        brand="VOLT",
        category="Casti In-Ear",
        price=139.0,
        tagline="Facute pentru miscare",
        description="Casti sport cu carlige de ureche sigure, rezistenta la transpiratie IP67 si sunet energic pentru antrenamente.",
        image=_E2,
        gallery=[_E2],
        specs={"Drivere": "10mm", "Autonomie": "10h + 30h", "Rezistenta": "IP67", "Conectivitate": "Bluetooth 5.3", "Greutate": "5.6g/bud"},
        colors=["#E63946", "#0A0A0A"],
        rating=4.6,
        reviews=884,
    ),
    _p(
        slug="volt-chrono-s",
        name="CHRONO S",
        brand="VOLT",
        category="Wearables",
        price=259.0,
        old_price=299.0,
        tagline="Ceas smart cu AMOLED",
        description="Smartwatch cu display AMOLED de 1.4 inch, GPS integrat, monitorizare SpO2 si peste 100 de moduri sportive.",
        image=_W1,
        gallery=[_W1],
        specs={"Display": "1.4 AMOLED", "Autonomie": "14 zile", "GPS": "Dual-band", "Rezistenta": "5ATM", "Senzori": "SpO2, HR, ECG"},
        colors=["#0A0A0A", "#8A8A8F"],
        rating=4.7,
        reviews=1567,
        featured=True,
        badge="Nou",
    ),
    _p(
        slug="volt-chrono-active",
        name="CHRONO ACTIVE",
        brand="VOLT",
        category="Wearables",
        price=189.0,
        tagline="Fitness, redefinit",
        description="Banda fitness usoara cu monitorizare continua a somnului si a stresului, notificari inteligente si autonomie de 20 de zile.",
        image=_W2,
        gallery=[_W2],
        specs={"Display": "1.1 AMOLED", "Autonomie": "20 zile", "Rezistenta": "5ATM", "Senzori": "HR, SpO2, Somn", "Greutate": "24g"},
        colors=["#0A0A0A", "#E63946", "#F3F4F6"],
        rating=4.5,
        reviews=990,
    ),
    _p(
        slug="volt-flux-charger",
        name="FLUX CHARGER",
        brand="VOLT",
        category="Accesorii",
        price=79.0,
        tagline="Statie de incarcare 3-in-1",
        description="Statie de incarcare wireless magnetica pentru telefon, casti si ceas simultan. Design minimalist din aluminiu.",
        image=_A1,
        gallery=[_A1],
        specs={"Putere": "15W + 5W + 5W", "Standard": "Qi2 Magnetic", "Porturi": "USB-C PD", "Material": "Aluminiu", "Cablu": "1.5m inclus"},
        colors=["#0A0A0A", "#F3F4F6"],
        rating=4.6,
        reviews=512,
    ),
    _p(
        slug="volt-cable-pro",
        name="CABLE PRO USB-C",
        brand="VOLT",
        category="Accesorii",
        price=29.0,
        tagline="Transfer si incarcare ultra-rapida",
        description="Cablu USB-C impletit cu invelis din nailon, suport pana la 240W si transfer de date USB4 la 40Gbps.",
        image=_A2,
        gallery=[_A2],
        specs={"Putere": "240W", "Date": "USB4 40Gbps", "Lungime": "2m", "Material": "Nailon impletit", "Conector": "USB-C la USB-C"},
        colors=["#0A0A0A", "#E63946"],
        rating=4.8,
        reviews=1730,
    ),
]
